"""
PDF report generation for a single screening result.

Builds a one-page PDF with the original/heatmap image, the grade,
confidence, lesion stats and advice - a tangible artifact for a
viva/demo, built with reportlab (pure Python, no system dependencies).
"""

import io
import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def build_report_pdf(heatmap_jpeg_bytes, grade, confidence, lesion_count,
                      lesion_density_pct, advice, mode, filename="screening"):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=20 * mm, bottomMargin=20 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#084f4f")
    )
    normal = styles["Normal"]
    small = ParagraphStyle("Small", parent=normal, fontSize=9, textColor=colors.grey)

    elements = []

    elements.append(Paragraph("Retina Guard AI &mdash; Screening Report", title_style))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        "Screening aid only &mdash; not a medical diagnosis. Always consult a qualified ophthalmologist.",
        small,
    ))
    elements.append(Spacer(1, 14))

    elements.append(Paragraph(f"<b>File analyzed:</b> {filename}", normal))
    elements.append(Paragraph(
        f"<b>Date:</b> {datetime.datetime.now().strftime('%d %b %Y, %I:%M %p')}", normal
    ))
    elements.append(Spacer(1, 10))

    img_buf = io.BytesIO(heatmap_jpeg_bytes)
    elements.append(RLImage(img_buf, width=110 * mm, height=110 * mm))
    elements.append(Spacer(1, 10))

    mode_label = "Trained EfficientNetB0 model" if mode == "trained-model" else "Heuristic demo (OpenCV)"

    data = [
        ["Severity grade", grade],
        ["Confidence", f"{confidence}%"],
        ["Lesions detected", str(lesion_count) if lesion_count is not None else "N/A"],
        ["Lesion area", f"{lesion_density_pct}%" if lesion_density_pct is not None else "N/A"],
        ["Analysis mode", mode_label],
    ]
    table = Table(data, colWidths=[55 * mm, 90 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eefbfb")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#084f4f")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 14))

    elements.append(Paragraph("<b>Recommendation</b>", normal))
    elements.append(Paragraph(advice, normal))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "Generated by Retina Guard AI (academic project demo). "
        "Highlighted regions in the image indicate areas the analysis flagged as possible lesions; "
        "they do not constitute a clinical finding.",
        small,
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()
